In [1]:
# imports

from scipy.io import loadmat
import numpy as np

In [2]:
# pré-carregamento

avi_data = list()
for i in range(1,6):
    avi_data.append(loadmat(f"datasets/avi/multi/Sub{i}_1_multitarget.mat"))

In [3]:
# extração direta dos dados

X = [d['Data'][0][0][7] for d in avi_data]
y = [d['Data'][0][0][8][0] for d in avi_data]

print(np.array(X).shape)

print("Divisão dos dados:")
for data in X:
    print(data.shape)

print("\nDivisão dos rótulos (sequências):")
for data in y:
    print(data)

(5, 8192, 10)
Divisão dos dados:
(8192, 10)
(8192, 10)
(8192, 10)
(8192, 10)
(8192, 10)

Divisão dos rótulos (sequências):
[7.5 8.2 7.  8.2 6.  7.5 6.  6.  8.2 8.2]
[7.5 8.2 7.  8.2 6.  7.5 6.  6.  8.2 8.2]
[7.5 8.2 7.  8.2 6.  7.5 6.  6.  8.2 8.2]
[7.5 8.2 7.  8.2 6.  7.5 6.  6.  8.2 8.2]
[7.5 8.2 7.  8.2 6.  7.5 6.  6.  8.2 8.2]
