## Carregamento de dataset de exemplo

Para exemplicação na disciplina, iremos trabalhar com o paradigma P300, utilizando o P300-Dataset do site [1].

Este dataset possui 8 participantes, e será carregado somente a base de dados de um deles para seguir com os exemplos.

A aplicação é de um speller (soletrador) 6x6, o qual foi utilizado nas seções experimentais, 7 palavras com 5 letras cada. Das 7 palavras, 3 foram utilizadas para treino e 4 para teste.

O equipamento utilizado foi o "g.Tec g.Nautilus g.LadyBird", com taxa de amostragem de 250 Hz, filtro `notch` de 50Hz (europeu) e filtro `bandpass` de 0.1 à 30 Hz.



In [5]:
# Carregamento do P300-dataset para o participante 8

from scipy.io import loadmat
import numpy as np

raw_data = loadmat('P300S08.mat')
raw_data.keys()

dict_keys(['__header__', '__version__', '__globals__', 'channelRange', 'Fs', 'Trials', 'stims', 'channelNames', 'sampleTime', 'samples', 'Word', 'data', 'subject'])

In [6]:
# Apresentando informações básicas presentes no dataset

# Taxa de amostragem
fs = raw_data['Fs'][0][0]
print(f'Taxa de amostragem: {fs} Hz')

# Canais utilizados
channels = raw_data['channelNames']
print('\nCanais utilizados: ', [str(name[0]) for name in channels[0]])
print('Número de canais: ', len(channels[0]))

Taxa de amostragem: 250 Hz

Canais utilizados:  ['FZ', 'CZ', 'P3', 'PZ', 'P4', 'PO7', 'PO8', 'OZ']
Número de canais:  8


In [36]:
# preparando os dados principais

main_data = raw_data['data'].copy()

X = main_data['X'][0][0]
y = main_data['y'][0][0].T[0]
trials = main_data['trial'][0][0][0]
flash = main_data['flash'][0][0]

print(X.shape)
print(y.shape)
print(trials.shape)
print(flash.shape)

(355904, 8)
(355904,)
(35,)
(4200, 4)


In [38]:
print(trials)

print(flash)

[  7478  17505  27533  37558  47580  57592  67628  77657  87682  97707
 107734 117759 127784 137808 147834 157860 167888 177910 187953 197955
 207987 218012 228037 238064 248088 258114 268138 278167 288194 298219
 308239 318275 328281 338317 348341]
[[  7478     32      7      1]
 [  7541     32      3      1]
 [  7604     32     10      1]
 ...
 [355682     31      3      2]
 [355745     31     10      1]
 [355807     31      4      1]]
